### PR TITLE
Enforce testing of secure password credentials

### LINKED ISSUE #1114: Enforce test coverage of SecureUsernamePasswordCredentials
Add a unit test leveraging the `SecureUsernamePasswordCredentials` type to perform a network operation against a private repository.

For inspiration, something similar can be peeked at **[here](https://github.com/libgit2/libgit2sharp/blob/63f8d6d90f06f4578604b57502f2c6b8aabf4479/LibGit2Sharp.Tests/CloneFixture.cs#L199-L223)**

/cc @ckuhn203

### PR DESCRIPTION
**Pull request by Therzok**
Fixes #1114

### CODE REVIEW

**Comment by nulltoken** [comment]
@Therzok Wow, you're fast!

Just a question regarding your commit message. Were you willing to start it with `Ensure` rather than `Encore`?

**Comment by nulltoken** [comment]
or `Enforce`?

**Comment by Therzok** [comment]
Note to self: Never code before morning coffee.

**Comment by Therzok** [comment]
Fixed coding styles issues too, I think it's good to go once CI tests it.

**Comment by nulltoken** [comment]
:heart:

**Comment by ckuhn203** [comment]
Wow. Fast it right. I didn't even get a chance to see @nulltoken's cc before this was done. =;)-

**Pull request merged**
