### PR TITLE
Add DebuggerDisplay attribute to TreeEntry

### PR DESCRIPTION
**Pull request by xoofx**
Just a debugger display for TreeEntry.

### CODE REVIEW

**Comment by nulltoken** [comment]
Thanks for this. The build is failing because this implementation doesn't follow our standard implementation pattern. The failing assertion message describes the expectation. Could you please take a look at it?

**Comment by xoofx** [comment]
Oops, sorry, this is fixed by last commit

**Comment by dahlbyk** [comment]
:+1:

**Comment by nulltoken** [comment]
:tada:

**Pull request merged**
