### PR TITLE
Checking that autocrlf settings are now honored on non Win platforms

### PR DESCRIPTION
**Pull request by nulltoken**

### CODE REVIEW

**Comment by nulltoken** [comment]
Related to https://github.com/libgit2/libgit2/pull/2798

/cc @Therzok @csware

**Comment by csware** [comment]
Please pull again and rebuild.

**Comment by nulltoken** [comment]
>Please pull again and rebuild.

@csware Thanks! Just done that.

**Comment by nulltoken** [comment]
Linux passes well! :tada: 

But 

OS X fails :skull: :fire: and I can't understand where do those regex.h errors come from (@carlosmn @ethomson  @Therzok any idea?)

**Comment by nulltoken** [comment]
Note to self: Reactivate this now that https://github.com/libgit2/libgit2/pull/3199 is merged

**Comment by ethomson** [comment]
This is quite out of date, and I don't feel a strong need to re-test things that are validated by libgit2.  Closing this.

**Pull request closed without merging**
