### PR TITLE
Make Repository.IsValid() return false on empty paths

### LINKED ISSUE #818: Repository.IsValid should not throw for null/empty argument
Currently `Repository.IsValid` throws an exception if the argument is null or empty. Rather than throw an exception, this method should simply return `false` in this case, similar to the behavior of [`Directory.Exists`](http://msdn.microsoft.com/en-us/library/system.io.directory.exists.aspx) or [`File.Exists`](http://msdn.microsoft.com/en-us/library/system.io.file.exists.aspx).

### PR DESCRIPTION
**Pull request by ptr1120**
Fix #818

### CODE REVIEW

**Comment by nulltoken** [comment]
Something went wrong, I think. The two commits are still there.

Something like this below should do the trick

```
git reset --soft HEAD~2
git commit
```

Either I can fix that for you and manually merge your PR, or you can try it out by yourself.

**Comment by ptr1120** [comment]
please fix it by your self, won't fix on my side...

**Comment by nulltoken** [comment]
@ptr1120 No problem. Thanks for the help and the thorough test coverage!

Cheers

**Comment by nulltoken** [comment]
Superseded by #1156

**Pull request closed without merging**
