### PR TITLE
Update to libgit2 v1.2.0

### PR DESCRIPTION
**Pull request by jairbubbles**
- Update `LibGit2Sharp.NativeBinaries` to `2.0.315-alpha.0.2`
- Quickly fix some breaking changes introduced by:
  -  https://github.com/libgit2/libgit2/pull/6016
  - https://github.com/libgit2/libgit2/pull/6012
  - https://github.com/libgit2/libgit2/pull/5405

### CODE REVIEW

**Comment by jairbubbles** [comment]
Hey @bording @A-Ovchinnikov-mx, I started to look at integrating the new versions but many tests are failing 😅

Some tests like `LibGit2Sharp.Tests.RebaseFixture.CanContinueRebase` do generate a `System.AccessViolationException` which is a bit worrying (cc @ethomson) 

I started to look at the `is_valid_name` depreciation but because of https://github.com/libgit2/libgit2/pull/6032 we cannot switch yet to the new version.

**Comment by jairbubbles** [comment]
Ok, thanks to https://github.com/libgit2/git2go/pull/777 I found the culprit for the memory corruption. A new callback was added (https://github.com/libgit2/libgit2/pull/6016) but it's not at the end of the struct.

**Comment by bording** [comment]
At some point I guess we'll need to turn those padding fields into actual things, but for now I'll just go ahead and merge this.

**Review by bording — APPROVED** [review]

**Comment by bording** [comment]
Before I push up a new preview package that uses this, I need to rip out all of the managed HTTPS implementation stuff added in #1618 and go back to using the native OpenSSL stuff. I should have some time this weekend to take a look at that.

**Pull request merged**
