### PR TITLE
GenerateNativeDll task: use file name from nuget

### PR DESCRIPTION
**Pull request by ethomson**
Use the `libgit2_filename.txt` from the NuGet package instead of
trying to derive it based on the hash.

Depends on https://github.com/libgit2/libgit2sharp.nativebinaries/pull/17

### CODE REVIEW

**Comment by shiftkey** [comment]
```
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL '4d6362b168cdbc7d5b734810f2c81020c2837c4a': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

Hrm

**Comment by bording** [comment]
Taking a quick look at this, I'm not sure it's going to work correctly yet. Did you look at the `NativeDllName.targets` file? The file that is being passed to the task there is the hash file. You'll also need to change that to point to your new ``libgit2_filename.txt` file.

**Comment by ethomson** [comment]
> Did you look at the NativeDllName.targets file?

Yeah, I neglected to include that change.  Thanks!

**Comment by nulltoken** [comment]
@ethomson Rebased. What should we do with this PR?

**Comment by ethomson** [comment]
Any reason not to merge it?

**Comment by nulltoken** [comment]
>Any reason not to merge it?

The build was previously failing. I've just fixed it :wink:

**Comment by ethomson** [comment]
:sparkles:  Thanks!

**Pull request merged**
