### PR TITLE
Leverage Travis built-in csharp language

### LINKED ISSUE #1082: Leverage Travis csharp language
Cf. http://docs.travis-ci.com/user/languages/csharp/

The mono runtime is downloaded/installed on each build (which amounts for a large portion of the build time on Mac Os X).

Let's try and leverage this feature to get a faster feedback loop

### PR DESCRIPTION
**Pull request by nulltoken**
Fix #1082

### CODE REVIEW

**Comment by carlosmn** [comment]
We have dependencies outside of mono, you can't remove the scripts which do that. The bit about mono can go away, but cmake and libgit2's deps still need to get installed.

**Comment by nulltoken** [comment]
@carlosmn Are you sure? Aren't we now depending on compiled native binaries through a NuGet package?

**Comment by carlosmn** [comment]
I'd forgotten about that.

Though it looks like a moot point since the Travis support mono seems to be restricted to Ubuntu derivatives, which OS X is not.

**Comment by nulltoken** [comment]
Ok. Current status is as follows:

**Linux:**
 - Mono 3.2.8: :white_check_mark: 
 - Mono 3.6.0: :boom: (Not supported yet by https://github.com/travis-ci/travis-build/blob/ff818cc8b5b76dbc2d045ec65177170e6ac5cca4/lib/travis/build/script/csharp.rb)
 - Mono 3.12.0: :white_check_mark:

**Mac Os X:**
 - Not supported. Yet? (cf. https://github.com/travis-ci/travis-ci/issues/3546)

/cc @Therzok

**Comment by akoeplinger** [comment]
@nulltoken "Mono 3.6.0: :boom: (Not supported yet by..)" -> this is because back then there were no official Debian packages from Xamarin for that version, they were only introduced with Mono 3.8. Travis supports every version that came after that, through Mono's [snapshot packages](http://www.mono-project.com/docs/getting-started/install/linux/#accessing-older-releases).

I'd suggest you also test against `latest` (via setting the `mono` key in .travis.yml), which floats to whatever the current Mono version is in Xamarin's repositories. `alpha` and/or `beta` might be a good idea as well to catch possible regressions in upcoming Mono versions.

**Comment by nulltoken** [comment]
@akoeplinger Thanks for the feedback!

>Travis supports every version that came after that, through Mono's snapshot packages.

@Therzok Could there be any chance to populate those with some older releases?

http://origin-download.mono-project.com/repo/debian/dists/wheezy/snapshots/

>I'd suggest you also test against latest 

Sadly, we're hitting some issue about this (see https://github.com/libgit2/libgit2sharp/pull/1034#issuecomment-97157386 and https://github.com/libgit2/libgit2sharp/issues/1067#issuecomment-108274452)

**Comment by Therzok** [comment]
@nulltoken I'm not sure we can release older versions, although we can ask @directhex.

**Comment by directhex** [comment]
> @Therzok Could there be any chance to populate those with some older releases?

It isn't possible to do that using the repository management software we're using - the snapshot facility is a strict snapshot in time of the state of the "main" repository, with no ability to insert history

**Pull request closed without merging**
