### PR TITLE
Added GitLink support

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by nulltoken** [comment]
@GeertvanHorrik Thanks for this. I've given it a try but didn't succeed in stepping in during debug. 

Then I realized that maybe the content of `/nuget.package/BuildNugetPackage.ps1` should be tweaked as well as part of this PR.

Thoughts?

**Comment by GeertvanHorrik** [comment]
You must put the pdb files inside the nuget package.

**Comment by nulltoken** [comment]
Could you please add the proposed changes below to your PR? Those should:

 - No longer build a symbol package
 - Embed the produced .pdb files in the package

```diff
diff --git a/nuget.package/BuildNugetPackage.ps1 b/nuget.package/BuildNugetPackage.ps1
index 5dac796..c5b623f 100644
--- a/nuget.package/BuildNugetPackage.ps1
+++ b/nuget.package/BuildNugetPackage.ps1
@@ -71,8 +71,7 @@ try {
   Run-Command { & "$(Join-Path $projectPath "..\Lib\NuGet\Nuget.exe")" Restore "$(Join-Path $projectPath "..\LibGit2Sharp.sln")" }
 
   # Cf. https://stackoverflow.com/questions/21728450/nuget-exclude-files-from-symbols-package-in-nuspec
-  Run-Command { & "$(Join-Path $projectPath "..\Lib\NuGet\Nuget.exe")" Pack -Build -Symbols "$(Join-Path $projectPath "LibGit2Sharp.csproj")" -Prop Configuration=Release -Exclude "**/NativeBinaries/**/*.*"}
-  Run-Command { & "$(Join-Path $projectPath "..\Lib\NuGet\Nuget.exe")" Pack "$(Join-Path $projectPath "LibGit2Sharp.csproj")" -Prop Configuration=Release }
+  Run-Command { & "$(Join-Path $projectPath "..\Lib\NuGet\Nuget.exe")" Pack -Build "$(Join-Path $projectPath "LibGit2Sharp.csproj")" -Prop Configuration=Release }
 }
 finally {
   Pop-Location
diff --git a/nuget.package/LibGit2Sharp.nuspec b/nuget.package/LibGit2Sharp.nuspec
index f605336..3b99741 100644
--- a/nuget.package/LibGit2Sharp.nuspec
+++ b/nuget.package/LibGit2Sharp.nuspec
@@ -24,5 +24,6 @@
     <file src="..\CHANGES.md" target="App_Readme\LibGit2Sharp.CHANGES.md" />
     <file src="..\nuget.package\build\*.*" target="build\net40" />
     <file src="..\Lib\NativeBinaries\libgit2.license.txt" target="App_Readme" />
+    <file src="bin\$configuration$\$id$.pdb" target="lib\net40" />
   </files>
 </package>
```

**Comment by GeertvanHorrik** [comment]
Done.

**Comment by nulltoken** [comment]
Hmmm. 

I've downloaded the NuGet package from the last AppVeyor build and created a small Console App
which references it locally.

```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using LibGit2Sharp;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine(GlobalSettings.Version);
            Console.ReadLine();
        }
    }
}
```

**Note:** *Enable source server support* is ticked in VS options.

I've set a breakpoint at the `Console.WriteLine()` level and hit F5.

Then I've hit F11 and got the following

image

@GeertvanHorrik What did I miss?

**Comment by GeertvanHorrik** [comment]
How can I get the latest AppVeyor nuget package? Then I can test it.

**Comment by nulltoken** [comment]
>How can I get the latest AppVeyor nuget package? Then I can test it.

Click on the latest AppVeyor build log, pick one of the jobs, click on the `Artifacts` tab, download and :tada:!

**Comment by GeertvanHorrik** [comment]
Seems like the pdbs are not updated. They should contain something similar like this:

```
SRCSRV: variables ------------------------------------------
SRCSRVVERCTRL=https
SRCSRVTRG=https://raw.github.com/Catel/Catel/260de28062897c0dbaaefd0b10f03737a99bbd25/%var2%
SRCSRV: source files ---------------------------------------
C:\CI_WS\Ws\74179\Source\Catel\src\Catel.Core\Catel.Core.Shared\ApiCop\ApiCop.cs*src/Catel.Core/Catel.Core.Shared/ApiCop/ApiCop.cs
C:\CI_WS\Ws\74179\Source\Catel\src\Catel.Core\Catel.Core.Shared\ApiCop\ApiCopListenerBase.cs*src/Catel.Core/Catel.Core.Shared/ApiCop/ApiCopListenerBase.cs
C:\CI_WS\Ws\74179\Source\Catel\src\Catel.Core\Catel.Core.Shared\ApiCop\ApiCopManager.cs*src/Catel.Core/Catel.Core.Shared/ApiCop/ApiCopManager.cs
```

**Comment by nulltoken** [comment]
Oh! I think they're actually overwritten by the `NuGet.exe` command. Could you please try to remove the `-Build` switch?

**Comment by GeertvanHorrik** [comment]
Done. Hope it's ok, this is becoming the hardest PR in my life.... ;-)

**Comment by Therzok** [comment]
Practice makes perfect. :D

**Comment by nulltoken** [comment]
Dammit!! I forgot to thin about this as well.

We also should drop the following

```
Clean-OutputFolder (Join-Path $projectPath "bin\")
Clean-OutputFolder (Join-Path $projectPath "obj\")
```

**Comment by nulltoken** [comment]
@GeertvanHorrik Ok, I've successfully stepped in while in debug mode.

@jamill @ethomson @therzork Can you please share your thoughts about this proposal?

**Comment by Therzok** [comment]
lgtm

**Comment by GeertvanHorrik** [comment]
http://www.urbandictionary.com/define.php?term=LGTM&utm_source=search-action

**Comment by nulltoken** [comment]
@GeertvanHorrik Thanks for this.

Because @ctaggart was the first to actually touch base with LibGit2Sharp (with #465 and #876), I think I'm going to rather consider #1009 over this one.

Cheers!

**Comment by GeertvanHorrik** [comment]
Next time please tell that in advance, would have saved me a lot of time which I could have put in other OS work.

**Pull request closed without merging**
