### PR TITLE
Linux: support broader range of distros/architectures by trying to load packed native libraries.

### PR DESCRIPTION
**Pull request by tmds**
LibGit2Sharp includes a number of native libraries that are built on different OSes.
These native libraries have a dependency on OpenSSL and the system c-library.

On x64, in case the Linux flavor is not known, a fallback is performed to the 'linux-x64' native library.
This library is built with a dependency on OpenSSL 1.0.
OpenSSL 1.0 is deprecated by OpenSSL 1.1, so on more recent version of Linux, the 'linux-x64' library fails to load.

On arm64, native libraries are currently included for debian.* (OpenSSL 1.1) and ubuntu.18.04 (OpenSSL 1.0).
Loading on other distros will fail.

In both cases LibGit2Sharp is probably including a library that works, but the default resolution logic
is not able to find it.

By using the 'NativeLibrary' class (.NET Core 3.0) we can extend the resolution logic, and try to load
the other native libraries that are packed with LibGit2Sharp.

### CODE REVIEW

**Comment by tmds** [comment]
cc @omajid @dagood @crummel

**Comment by ethomson** [comment]
Jesus, LibGit2Sharp needs to 🔥 the dependency on OpenSSL.

**Comment by tmds** [comment]
> LibGit2Sharp needs to 🔥 the dependency on OpenSSL.

The dependency comes from libgit2.

**Comment by ethomson** [comment]
> > LibGit2Sharp needs to 🔥 the dependency on OpenSSL.

> The dependency comes from libgit2.

Yes, I'm aware.  But libgit2 can use myriad options for HTTPS, including [a custom one](https://github.com/libgit2/libgit2sharp/pull/1618).

**Comment by tmds** [comment]
> But libgit2 can use myriad options for HTTPS, including a custom one.

That's a nice feature, and it will solve the main reason for load failures.

**Comment by tmds** [comment]
CI on Windows has a failed test:
```
D:\a\1\s>dotnet test "D:\a\1\s\LibGit2Sharp.Tests/LibGit2Sharp.Tests.csproj" -f netcoreapp2.1 --no-restore --no-build 
Test run for D:\a\1\s\bin\LibGit2Sharp.Tests\Release\netcoreapp2.1\LibGit2Sharp.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.9.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:11.42]     LibGit2Sharp.Tests.CloneFixture.CanInspectCertificateOnClone(url: "git@github.com:libgit2/TestGitRepository.git", hostname: "github.com", certType: typeof(LibGit2Sharp.CertificateSsh)) [SKIP]
Skipped  LibGit2Sharp.Tests.CloneFixture.CanInspectCertificateOnClone(url: "git@github.com:libgit2/TestGitRepository.git", hostname: "github.com", certType: typeof(LibGit2Sharp.CertificateSsh))
[xUnit.net 00:00:15.26]     LibGit2Sharp.Tests.CloneFixture.CanCloneWithCredentials [SKIP]
Skipped  LibGit2Sharp.Tests.CloneFixture.CanCloneWithCredentials
[xUnit.net 00:00:22.40]     LibGit2Sharp.Tests.RepositoryFixture.CanListRemoteReferencesWithCredentials [SKIP]
Skipped  LibGit2Sharp.Tests.RepositoryFixture.CanListRemoteReferencesWithCredentials
[xUnit.net 00:00:32.80]     LibGit2Sharp.Tests.FetchFixture.CanFetchIntoAnEmptyRepositoryWithCredentials [SKIP]
Skipped  LibGit2Sharp.Tests.FetchFixture.CanFetchIntoAnEmptyRepositoryWithCredentials
[xUnit.net 00:01:07.51]     LibGit2Sharp.Tests.StageFixture.CanStageANewFileWithAFullPath(ignorecase: True) [SKIP]
Skipped  LibGit2Sharp.Tests.StageFixture.CanStageANewFileWithAFullPath(ignorecase: True)
[xUnit.net 00:01:16.44]     LibGit2Sharp.Tests.DiffTreeToTreeFixture.RenameDetectionObeysConfigurationSetting [SKIP]
Skipped  LibGit2Sharp.Tests.DiffTreeToTreeFixture.RenameDetectionObeysConfigurationSetting
[xUnit.net 00:02:51.08]     LibGit2Sharp.Tests.ResetHeadFixture.SoftResetSetsTheHeadToTheSpecifiedCommit [FAIL]
Failed   LibGit2Sharp.Tests.ResetHeadFixture.SoftResetSetsTheHeadToTheSpecifiedCommit
Error Message:
 Assert.InRange() Failure
Range:  (9/9/2019 3:00:24 PM +00:00 - 9/9/2019 3:00:24 PM +00:00)
Actual: 9/9/2019 3:00:23 PM +00:00
Stack Trace:
   at LibGit2Sharp.Tests.TestHelpers.BaseFixture.AssertRefLogEntry(IRepository repo, String canonicalName, String message, ObjectId from, ObjectId to, Identity committer, DateTimeOffset before) in D:\a\1\s\LibGit2Sharp.Tests\TestHelpers\BaseFixture.cs:line 471
   at LibGit2Sharp.Tests.ResetHeadFixture.AssertSoftReset(Func`2 branchIdentifierRetriever, Boolean shouldHeadBeDetached, Func`2 expectedHeadNameRetriever) in D:\a\1\s\LibGit2Sharp.Tests\ResetHeadFixture.cs:line 128
[xUnit.net 00:02:57.00]     LibGit2Sharp.Tests.GlobalSettingsFixture.LoadFromSpecifiedPath(architecture: "x86") [SKIP]
[xUnit.net 00:02:57.01]     LibGit2Sharp.Tests.GlobalSettingsFixture.LoadFromSpecifiedPath(architecture: "x64") [SKIP]
Skipped  LibGit2Sharp.Tests.GlobalSettingsFixture.LoadFromSpecifiedPath(architecture: "x86")
Skipped  LibGit2Sharp.Tests.GlobalSettingsFixture.LoadFromSpecifiedPath(architecture: "x64")
[xUnit.net 00:03:11.74]     LibGit2Sharp.Tests.NetworkFixture.CanListRemoteReferencesWithCredentials [SKIP]
Skipped  LibGit2Sharp.Tests.NetworkFixture.CanListRemoteReferencesWithCredentials

```

**Comment by tmds** [comment]
Independent of getting rid of the OpenSSL dependency, this change has value. For example, when new releases of Alpine are made (which the rid graph doesn't yet map to `linux-musl-x64`), they fall back to `linux-x64` which doesn't work.

**Comment by ethomson** [comment]
Sure, sorry, I was idly speculating / complaining, I wasn't suggesting that any other changes should preclude merging it.  But @bording understands this stuff much better than I, so I'll leave it to him.

**Comment by tmds** [comment]
@bording can you take a look?

We've hit this a few times when bringing .NET Core to new versions of Fedora (which causes the mapping to `fedora-x64` to fail).
And now also when trying out .NET Core on arm64 on Fedora (because there isn't a `fedora-arm64`).

**Comment by bording** [comment]
@tmds I've been rather busy recently and haven't had much spare time to devote to LibGit2Sharp recently, but I'll try and take a look at this soon.

I'm curious where you've hit problems with this, though. Where in .NET Core are you running into a LibGit2Sharp dependency? It was my understanding that that the only place was in the Source Link packages, but those have since removed LibGit2Sharp entirely.

**Comment by tmds** [comment]
https://github.com/dotnet/source-build/issues/1083 describes the issues with source-build.

The issue applies to any app using libgit2sharp that is meant to work on a broad range of linux-x64/linux-arm64.

**Comment by bording** [comment]
So this is an interesting change, and I had been following the `NativeLibrary` stuff in .NET Core 3.0 with an idea towards being able to leverage it in some way.

The NativeBinaries package has always had to walk the tightrope of ensuring as many distros as possible are covered, without also completely exploding the size of the package by building a library for each possible RID. That means that I've had to pay a lot of attention to the RID graph to figure out how a given distro gets mapped in there. And, as you've observed, it's a moving target, so we're always having to play catch up.

I think what this really demonstrates is that .NET Core's RID mechanism needs improvement, but I know there are already open issues about that.

As a first step, I think it makes sense to make this change. Eventually, I'd be inclined to add a `netcoreapp3.0` target instead of using reflection, but that can always be done later.

**Comment by bording** [comment]
This has been published on NuGet.org as [0.27.0-preview-0020](https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0020).

**Comment by tmds** [comment]
> This has been published on NuGet.org as 0.27.0-preview-0020.

**Comment by tmds** [comment]
> This has been published on NuGet.org as 0.27.0-preview-0020.

I tinkered with my `/etc/os-release` and unknown future Fedora versions can use LibGit2Sharp!

> I think what this really demonstrates is that .NET Core's RID mechanism needs improvement, but I know there are already open issues about that.

Agree. This is the main one: https://github.com/NuGet/Home/issues/5862.

**Comment by tanmay-18** [comment]
> This has been published on NuGet.org as [0.27.0-preview-0020](https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0020).

Issue still persists with 'git2-7ce88e6' dll not found.

**Pull request merged**
