### PR TITLE
Correct ".NET" usage

### PR DESCRIPTION
**Pull request by richlander**
- ".Net" -> ".NET".
- Make fully upper-case, which is the correct usage.

Note: Would be great if a project owner could make the same change in the repo description. PRs cannot affect that.

### CODE REVIEW

**Comment by ethomson** [comment]
While we're talking description:  are .NET and Mono distinct?  Should this not just be "to .NET"?

**Comment by nulltoken** [comment]
> While we're talking description: are .NET and Mono distinct? Should this not just be "to .NET"?

/cc @Therzok ?

**Comment by nulltoken** [comment]
@richlander Thanks! 

Repository description has been updated.

**Comment by Therzok** [comment]
@nulltoken It's actually dependent on what you're trying to say. If you're trying to mention a runtime, then it's Mono/CoreCLR/CLR. If you're trying to mention the .NET stack, it's .NET.

**Comment by nulltoken** [comment]
@Therzok Hmmm... So, what would be correct wording to express that the library is compatible with both the Mono project and Microsoft implementations of the runtime?

/cc @ethomson @richlander

**Comment by richlander** [comment]
I suggest removing Mono from the repo description at the top, just to make it simpler. it's really a statement about this project being the language bindings for .NET at large.

It is important to be clear about .NET and Mono in the readme, since that describes a particular usage scenario.

@migueldeicaza is free to overrule me.

**Comment by migueldeicaza** [comment]
Isn't .NET a Microsoft trademark for a particular implementation?

Perhaps a task for the .NET foundation to bless various VMs implementing some/parts of the spec as being .NET or not?

But in the meantime, I do not think it hurts to put both Mono and .NET there.

**Comment by richlander** [comment]
Works for me!

**Comment by nulltoken** [comment]
>Perhaps a task for the .NET foundation to bless various VMs implementing some/parts of the spec as being .NET or not?

/cc  @martinwoodward 

Meanwhile, let's merge this in. 

Cheers!

**Comment by martinwoodward** [comment]
Thanks for the CC - I'll add certification to my list of things to look into.

**Pull request merged**
