### PR TITLE
NuGet improvements.

### PR DESCRIPTION
**Pull request by Zoltu**
* Adds a new project to the solution for building a native NuGet package.
 * The package ends up in `bin\<configuration>`.
 * When the package is installed, a build target file is imported into the target project that will cause the binaries to be copied to `$(TargetPath)` after build (if necessary).
 * Versioned as the last version of the LibGit2 that was pulled into this repository.
 * Do not be fooled, this is not actually a .csproj. In order to get Visual Studio to load it so that it shows up in Solution Explorer you have to tag it as one of a known list of project file types (http://msdn.microsoft.com/en-us/library/vstudio/ms171468(v=vs.110).aspx).  If you try to view the properties on it, Visual Studio will add a bunch of stuff to the underlying project file.  I don't *think* anything will break, but if it adds back the imports I believe it will break.  Be aware, best to just not open the properties on the project and instead open it in a text editor.

* Changes NuGet package to be generated on successful build of the class library.
 * The package ends up in `bin\<configuration>`.
 * Depends on the Native NuGet package (see above).
 * Only installs the one library and the one dependency, nothing fancy.

* Adds dependency on `NuGet for MSBuild`.
 * Both projects have a `.targets` file added to them that utilizes `NuGet for MSBuild`.
 * Take care in updating `NuGet for MSBuild`, it will add some post-build tasks to your project when you install/update it.  I have removed these but they will come back if you update.  They may have undesired side effects.
 * I have committed the dependency to the repo, I would encourage you (project owners) to `.gitignore` `packages/` though since Visual Studio will restore them on first build automatically (since VS2012 Update ? I believe).

### CODE REVIEW

**Comment by Zoltu** [comment]
Re-create of PR #778.

**Comment by Zoltu** [comment]
Once #894 is merged this PR should be modified to leverage automatic package restoration.  I can take care of this once #894 is merged.

**Comment by Zoltu** [comment]
Currently failing due to a bug in xbuild.  It looks exactly like the previous one I reported https://bugzilla.xamarin.com/show_bug.cgi?id=22981 but that is supposedly fixed in Mono 3.10.  I have not spent much time investigating further.
```
Tool NuGet.exe execution started with arguments: pack /Users/travis/build/libgit2/libgit2sharp/NativeNuGet/NativeNuGet.nuspec -Version 0.21.3 -BasePath bin/Release/ -OutputDirectory bin/Release/ -NonInteractive -Prop Configuration="Release" -Prop Platform="AnyCPU" -NoPackageAnalysis 
/Users/travis/build/libgit2/libgit2sharp/packages/NuGet.for.MSBuild.1.4.3/build/NuGet.for.MSBuild.targets: error : Error executing tool 'NuGet.exe': ApplicationName='NuGet.exe', CommandLine='pack /Users/travis/build/libgit2/libgit2sharp/NativeNuGet/NativeNuGet.nuspec -Version 0.21.3 -BasePath bin/Release/ -OutputDirectory bin/Release/ -NonInteractive -Prop Configuration="Release" -Prop Platform="AnyCPU" -NoPackageAnalysis ', CurrentDirectory='/Users/travis/build/libgit2/libgit2sharp/NativeNuGet', Native error= Cannot find the specified file
```

**Comment by Therzok** [comment]
By the looks of it, https://github.com/mono/mono/commit/7439e997ac1f2e40c6b9e1fab43d24b8c07f0561 doesn't seem to be in 3.10.

**Comment by Therzok** [comment]
See [this](https://github.com/mono/mono/commits/mono-3.10.0-branch) for reference.

**Comment by Zoltu** [comment]
You are correct, my mistake.  I'll go back to waiting then.

**Comment by Therzok** [comment]
The fix is in 3.12 mono, so if this can wait until then, it's all perfect.

**Comment by nulltoken** [comment]
Superseded by #984

**Comment by nulltoken** [comment]
Cheers!

**Pull request closed without merging**
