### PR TITLE
Fix for locating lib folder on netcore

### LINKED ISSUE #1498: MsBuild, Native binaries and AppContext.BaseDirectory.
I am working on the `GitVersion` msbuild task. It's distrubuted as a nuget package. The nuget package contains a build of the task assembly for `net461` and a build for `netstandard1.5`.
The corresponding `libgit2sharp` assembly (which our task depends on) and the `/lib` folder containing the native binaries that `libgit2sharp` requires, lives alongside the task assembly, in the nuget package.

When the `nuget` package is added to a project, and the project is built within VS - this uses the full desktop version of msbuild, and subsequently the `net461` assembly containing the `GitVersion` build task is loaded from the nuget package, and the task runs successfully - LibGit2sharp all works smoothly.

However when dropping to the command line and running `dotnet build` (I am using version 2.0.2 of the dotnet sdk) this runs `msbuild` on `netcoreapp` and thus the `netstandard1.5` task assembly from the nuget package is loaded. In this scenario the task msbuild fails and this is the stack trace:

```
       Using "GetVersion" task from the task factory "NuGetTaskRunnerFactory".
       Task "GetVersion"
         Resolved GitVersionTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitVersionTask.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitVersionTask.dll.
         Resolved GitVersionCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitVersionCore.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitVersionCore.dll.
         Resolved GitTools.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitTools.Core.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\GitTools.Core.dll.
         Resolved LibGit2Sharp, Version=0.25.0.0, Culture=neutral, PublicKeyToken=7cbde695407f0333 located in C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\LibGit2Sharp.dll and loaded from C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\LibGit2Sharp.dll.
     1>MSBUILD : warning : WARN [10/24/17 20:59:04:58] Could not determine assembly version: System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.LoadNativeLibrary()\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods..cctor()\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    --- End of inner exception stack trace ---\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_buf_free(GitBuf buf)\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.Proxy.ConvertPath(Func`2 pathRetriever)\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Repository.Discover(String startingPath)\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at GitVersion.GitPreparer.GetDotGitDirectory() in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\GitPreparer.cs:line 139\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at GitVersion.ExecuteCore.ExecuteGitVersion(String targetUrl, String dynamicRepositoryLocation, Authentication authentication, String targetBranch, Boolean noFetch, String workingDirectory, String commitId, Config overrideConfig, Boolean noCache) in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\ExecuteCore.cs:line 32\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at GitVersion.ExecuteCore.TryGetVersion(String directory, VersionVariables& versionVariables, Boolean noFetch, Authentication authentication) in C:\Users\Darrell\Source\Repos\GitVersion\src\GitVersionCore\ExecuteCore.cs:line 81 [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
       Done executing task "GetVersion".

```

From the stack trace, it shows that the `libgit2sharp` assembly is being loaded from alongside the task assembly: `C:\Users\Darrell\.nuget\packages\gitversiontask\0.0.1-alpha0003\build\netstandard1.5\LibGit2Sharp.dll`

It also shows this:

```
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'git2-15e1193': The specified module could not be found. (Exception from HRESULT: 0x8007007E)\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()\r [C:\Users\Darrell\Documents\visual studio 2017\Projects\ClassLibrary7\ClassLibrary7.csproj]
MSBUILD : warning :    at LibGit2Sharp.Core.NativeMethods.LoadNativeLibrary()\r 

```

Yet alongside the` libgit2sharp` assembly I have confirmed that there is a `lib` folder containing all of the native binaries - including `git2-15e1193.dll`:

image

Any ideas? @bording  ?

If you need to replicate, you can do so by taking my [PR branch](https://github.com/GitTools/GitVersion/pull/1269) of gitversion, calling `msbuild /t:Pack` on the msbuild task project to produce a nuget package containing libgit2sharp, then adding that nuget package to a sample .csproj file that has an initialised .git repository with atleast 1 commit, and building.

### PR DESCRIPTION
**Pull request by dazinator**
This fixes #1498

### CODE REVIEW

**Comment by bording** [comment]
As I've already mentioned, the lib folder isn't going to be around for .NET Core, so we'll need to come up with some other solution.

**Comment by dazinator** [comment]
This is aimed to be a hotfix to enable msbuild tasks that leverage `libgit2sharp` to run under `dotnet build`, today.

Not trying to dictate how you chose to address this longer term / in the future once /lib is removed.

**Comment by dazinator** [comment]
If the decision is not to adopt this fix, I am happy to switch `gitversion` over to a fork, until you have something in place perhaps? It's a bit of a pain but I guess that is the beauty of open source :-)

**Comment by bording** [comment]
The problem is that this isn't even a good enough temporary fix, because it won't work on non-windows platforms at all. 

I think it makes sense to figure out to handle this MSBuild properly vs. temp fixes and forks.

**Comment by bording** [comment]
Considering that Nerdbank.GitVersioning is working properly with .NET Core without needing changes makes me think the solution isn't to change LibGit2Sharp.

**Comment by dazinator** [comment]
Nerdbank.Gitversioning gets around this by adding some plumbing code to its base msbuild task that loads another copy of the same assembly into an assembly load context, at which point it uses a custom resolver to load find the dependencies. The task then proxies the input / outputs and execute call to the task that it loaded in the assembly load context (i.e it.proxies to itself). This proxying suffered from casting issues for example I tried with various sdk versions (1.0.0 to 2.0.2) and nerdbank.gitversion task had casting exceptions on some of them.

You can see all the logic here: https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/MSBuildExtensionTask/ContextAwareTask.cs

I notice it seems to set an environment variable for resolving unmanaged assemblies. I will have to look at the code but I wonder if libgit2sharp honours an environment variable..

The fix I put in place fixes my issue on windows. I'm not sure why exactly it needs to be wrapped in a windows only check though.. pretty sure it could work on other platforms the same way as well?

**Comment by dazinator** [comment]
Not sure why the travis build failed.. Seems to be a problem with nuget restore. Don't think it's anything I have permissions to fix.

**Comment by dazinator** [comment]
> The problem is that this isn't even a good enough temporary fix, because it won't work on non-windows platforms at all.

I am closing this, as I think you are right. Fixing this for windows only is not a good enough solution. 
If I need this fix for the interim period, I'll publish a temporary nuget package from my fork, which I will leave unlisted on nuget, and clearly named with my fork.

**Comment by bording** [comment]
> If libgit2sharp exposed a way for the consumer to configure where it should look for its native assemblies that could be another way to solve this.

FYI, a primary blocker from doing this is that the library search path can't be altered from within the process on unix like it can be from Windows. Once the process has been started, it's too late to alter it.

**Comment by dazinator** [comment]
> FYI, a primary blocker from doing this is that the library search path can't be altered from within the process on unix like it can be from Windows. Once the process has been started, it's too late to alter it.

Thanks for the info, that makes sense.

I think I have come to the conclusion that the only way to handle this for the msbuild task scenario, is to have your msbuild task assembly loaded into and executed from a custom 'AssemblyLoadContext':
 https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md#pinvoke-resolution

I've raised an issue over on UtilPack: https://github.com/CometaSolutions/UtilPack/issues/14 as I think it's something the msbuild task factory can take care of there. Happy for you to close this.

**Comment by bording** [comment]
> I think I have come to the conclusion that the only way to handle this for the msbuild task scenario, accross all platforms, is to have the msbuild task assembly loaded into, and executed from, a custom 'AssemblyLoadContext':

That does appear to be how Nerdbank.GitVersioning has handled it: https://github.com/AArnott/Nerdbank.GitVersioning/blob/master/src/MSBuildExtensionTask/ContextAwareTask.cs#L72

**Comment by dazinator** [comment]
Yup. I just feel strongly that putting this logic in the msbuild task itself is probably the wrong place. MsBuild tasks shouldn't have to be concerned with also being a proxy to themselves imho - they have enough to worry about. I also am not interested in compiling for netcore, I want to have a single compilation for netstandard! Huge respect to AArnott for the solution though - I am not dissing, just expressing my artistic licence :-)

**Pull request closed without merging**
