### PR TITLE
NuGet packages are no longer generated on AppVeyor

### PR DESCRIPTION
**Pull request by nulltoken**
Latest published package has been successfully performed with https://ci.appveyor.com/project/libgit2/libgit2sharp/build/868

Stopped working with https://ci.appveyor.com/project/libgit2/libgit2sharp/build/890

Which seems to put the issue in https://github.com/libgit2/libgit2sharp/compare/77691c271a87c4493d3e0146dda53ec231797e88...2a283297ee33cfa2e819577146934f483a6c189c

### CODE REVIEW

**Comment by ethomson** [comment]
:+1:

**Comment by nulltoken** [comment]
Let's see now if that hack worked...

**Comment by nulltoken** [comment]
Duh :sob: 

That didn't work. The **[build jobs](https://ci.appveyor.com/project/libgit2/libgit2sharp)** of the merge of this PR still displays:

```
Should package Nuget artifact = False
```

@FeodorFitsner Could you please help me troubleshoot this? Am I misinterpreting the AppVeyor variables or just unable do correclty write PowerShell?

**Comment by nulltoken** [comment]
@FeodorFitsner FWIW it's a rhetorical question: I'm bad at PowerShell'ing. What this PR shows if that's completely possible I could also be bad at reading the docs. However, I'd really appreciate any help you could me provide me with...

/cc @dahlbyk

**Comment by FeodorFitsner** [comment]
I'd do just:

$Env:SHOULD_PACKAGE_NUGET_ARTIFACT = -not $Env:APPVEYOR_PULL_REQUEST_NUMBER -and -not $Env:APPVEYOR_SCHEDULED_BUILD

**Comment by nulltoken** [comment]
@FeodorFitsner That worked wonderfully. Thanks!

**Pull request merged**
