### PR TITLE
Fix random build failure due to System.IO.FileSystem not found

### PR DESCRIPTION
**Pull request by AArnott**
Applies fix for https://github.com/AArnott/CodeGeneration.Roslyn/issues/25

### CODE REVIEW

**Comment by AArnott** [comment]
I see the Travis CI failure from this. Very odd as I wouldn't expect this to cause a build failure, and the failure in particular looks unrelated to the change. But I'll look more into it.

**Comment by AArnott** [comment]
I found a machine I could repro the problem on. I had forgotten that "no project info for P2P" is code for "the build failed on the referenced project".

**Comment by AArnott** [comment]
Evidently I inadvertently targeted a newer (1.0.5 instead of 1.0.4) version of the CoreCLR runtime.

**Comment by AArnott** [comment]
The Mac build [failed](https://travis-ci.org/libgit2/libgit2sharp/jobs/246982822#L1064) due to what appears to be an unrelated issue:

```
[xUnit.net 00:01:19.0662249]     LibGit2Sharp.Tests.CheckoutFixture.CheckoutCurrentReference [FAIL]
[xUnit.net 00:01:19.0676401]       Assert.InRange() Failure
[xUnit.net 00:01:19.0677293]       Range:  (6/26/17 6:45:22 AM +00:00 - 6/26/17 6:45:22 AM +00:00)
[xUnit.net 00:01:19.0677729]       Actual: 6/26/17 6:45:21 AM +00:00
[xUnit.net 00:01:19.0694405]       Stack Trace:
[xUnit.net 00:01:19.0709012]         /home/travis/build/libgit2/libgit2sharp/LibGit2Sharp.Tests/TestHelpers/BaseFixture.cs(458,0): at LibGit2Sharp.Tests.TestHelpers.BaseFixture.AssertRefLogEntry(IRepository repo, String canonicalName, String message, ObjectId from, ObjectId to, Identity committer, DateTimeOffset before)
[xUnit.net 00:01:19.0710105]         /home/travis/build/libgit2/libgit2sharp/LibGit2Sharp.Tests/CheckoutFixture.cs(873,0): at LibGit2Sharp.Tests.CheckoutFixture.CheckoutCurrentReference()
Failed   LibGit2Sharp.Tests.CheckoutFixture.CheckoutCurrentReference
Error Message:
 Assert.InRange() Failure
Range:  (6/26/17 6:45:22 AM +00:00 - 6/26/17 6:45:22 AM +00:00)
Actual: 6/26/17 6:45:21 AM +00:00
Stack Trace:
   at LibGit2Sharp.Tests.TestHelpers.BaseFixture.AssertRefLogEntry(IRepository repo, String canonicalName, String message, ObjectId from, ObjectId to, Identity committer, DateTimeOffset before) in /home/travis/build/libgit2/libgit2sharp/LibGit2Sharp.Tests/TestHelpers/BaseFixture.cs:line 458
   at LibGit2Sharp.Tests.CheckoutFixture.CheckoutCurrentReference() in /home/travis/build/libgit2/libgit2sharp/LibGit2Sharp.Tests/CheckoutFixture.cs:line 873
```

Any ideas, @bording?

**Comment by AArnott** [comment]
This seems non-deterministic as well, since [it passed](https://travis-ci.org/AArnott/libgit2sharp/builds/246981846) on my own travis CI account.

**Comment by ethomson** [comment]
I'll kick it.  I have yet to comprehend how we're ticking back in time but alas, we sometimes do.

**Comment by AArnott** [comment]
Thanks, @ethomson

**Comment by bording** [comment]
I've seen that kind of failure before. I wonder if its some sort of rounding/truncation error? For example, one code path rounds up to 22 seconds, and another truncates to 21.

**Comment by AArnott** [comment]
Ping?

**Pull request merged**
