### PR TITLE
Update libgit2 natives to 1.0.157

### PR DESCRIPTION
**Pull request by ethomson**
Use the new nuget package layout for .NET Core compatibility with
native binaries.

### CODE REVIEW

**Comment by ethomson** [comment]
Well, in what I'm sure will be SHOCKING NEWS, this has absolutely no effect for me when using a new-style (`project.json` based) project targeting .NET 4.5.1.

(Yay, nuget!)

@bording I think I've reached and surpassed both my limit of comprehension here and my patience with nuget.  Any chance you can provide me with some of your wisdom?

**Comment by bording** [comment]
I'm getting ready to go out of town for the rest of the week, and won't have access to a computer, but I'll definitely take a look at it when I get back.

**Comment by ethomson** [comment]
<3

**Comment by ethomson** [comment]
Okay, it turns out that you can't use an RID of `win-x64`, for net45 you simply must use `win7-x64` and `win7-x86` regardless of what version of Windows you're actually on.

Don't try to understand, just let it wash over you.

In any case, we now produce a `LibGit2Sharp.NativeBinaries` package that has a layout of `runtimes/{rid}/natives`, which is compatible with a new-style MSBuild-less `project.json` world.  On old-school `.csproj` based builds, we still run the `.props` which will take the binaries for the appropriate platform out of the `NativeBinaries` location and place it in a folder `lib` beneath the build target.  (We do *not* emulate the `runtimes/` strategy when we do the copy, because that would leave us liable to regress #1170 , instead we stick with `lib`).

I tested this with old style (`.csproj`) projects on a couple of platforms (Windows and Mono) and with new style (`project.json`) project on Windows.

I'm going to merge this so that I can build a proper nuget prerelease package and upload it.

**Comment by bording** [comment]
@ethomson Glad to see that you figured out the problem, despite the craziness around the RID usage. How did you manage to track it down to `win-x64` vs. `win7-x64` being the problem?

**Pull request merged**
