### PR TITLE
Fix compilation warning

### PR DESCRIPTION
**Pull request by nulltoken**

### CODE REVIEW

**Comment by shiftkey** [comment]
@nulltoken this all seems :sparkles: - anything in particular you'd like us to review here?

**Comment by nulltoken** [comment]
Some of those are quite trivial.

But I'd really appreciate if somenone (maybe @jamill) could especially review the `RevertFixture` and `RebaseOperationImpl` changes to make sure that I didn't miss anything.

:pray:

**Comment by jamill** [comment]
:sparkles: :+1:

**Comment by nulltoken** [comment]
@shiftkey @jamill Thanks for the feedback

**Pull request merged**
