### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by bording**
Also includes a minor tweak to the editorconfig file.

### CODE REVIEW

**Comment by ethomson** [comment]
With the travis update to require a newer .NET Core, am I right in thinking that we are now no longer .NET Core 2.0 compatible?  What's pushing that requirement?  What is the fallout from that?

**Comment by bording** [comment]
The reason for that is to get a newer SDK, which is needed for the switch to Microsoft.SourceLink.GitHub. 

That has no impact on the compatibility of the library. That's determined by the TFMs we target, which hasn't changed. The library is still `netstandard2.0`.

**Comment by bording** [comment]
It appears that all of the AppVeyor builds on the libgit2 account are getting stuck at being queued, but never actually run.

I've opened https://help.appveyor.com/discussions/problems/16035-queued-builds-never-start, so hopefully they'll be able to fix the problem.

**Comment by bording** [comment]
AppVeyor fixed the problem with the build queue!

**Comment by ethomson** [comment]
Yep, makes sense.  Thanks @bording.

**Pull request merged**
