### PR TITLE
Make sure treechanges and statuses are case-sensitive

### PR DESCRIPTION
**Pull request by yorah**
This behavior has been discussed in #344.

### CODE REVIEW

**Comment by nulltoken** [comment]
@yorah Thanks for the rebase. However, could you please just take care of fixing the following errors?

```
"C:\projects\libgit2sharp\LibGit2Sharp.sln" (default target) (1) ->
"C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj" (default target) (3) ->
(CoreCompile target) -> 
  StatusFixture.cs(453,38): error CS0029: Cannot implicitly convert type 'string' to 'LibGit2Sharp.Repository' [C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj]
  StatusFixture.cs(465,71): error CS0103: The name 'DummySignature' does not exist in the current context [C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj]
  StatusFixture.cs(465,87): error CS0103: The name 'DummySignature' does not exist in the current context [C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj]
  StatusFixture.cs(476,30): error CS1928: 'LibGit2Sharp.Index' does not contain a definition for 'RetrieveStatus' and the best extension method overload 'LibGit2Sharp.RepositoryExtensions.RetrieveStatus(LibGit2Sharp.IRepository)' has some invalid arguments [C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj]
  StatusFixture.cs(476,30): error CS1929: Instance argument: cannot convert from 'LibGit2Sharp.Index' to 'LibGit2Sharp.IRepository' [C:\projects\libgit2sharp\LibGit2Sharp.Tests\LibGit2Sharp.Tests.csproj]
```

**Comment by nulltoken** [comment]
Fix proposal

```diff
diff --git a/LibGit2Sharp.Tests/StatusFixture.cs b/LibGit2Sharp.Tests/StatusFixture.cs
index d818873..6bd172a 100644
--- a/LibGit2Sharp.Tests/StatusFixture.cs
+++ b/LibGit2Sharp.Tests/StatusFixture.cs
@@ -445,12 +445,12 @@ FileStatus expectedCamelCasedFileStatus
         [SkippableFact]
         public void RetrievingStatusMustAlwaysBeCaseSensitive()
         {
-            SelfCleaningDirectory scd = BuildSelfCleaningDirectory();
-
             InconclusiveIf(() => IsFileSystemCaseSensitive,
                 "Skipping 'ignorecase = true' test on case-sensitive file system.");
 
-            using (Repository repo = Repository.Init(scd.DirectoryPath))
+            string repoPath = InitNewRepository();
+
+            using (Repository repo = new Repository(repoPath))
             {
                 repo.Config.Set("core.ignorecase", true);
 
@@ -462,22 +462,23 @@ public void RetrievingStatusMustAlwaysBeCaseSensitive()
 
                 Tree treeOld = repo.ObjectDatabase.CreateTree(tdOld);
 
-                var commit = repo.ObjectDatabase.CreateCommit("blah", DummySignature, DummySignature, treeOld, new Commit[] { });
+                var commit = repo.ObjectDatabase.CreateCommit(
+                    Constants.Signature, Constants.Signature, "blah", treeOld, new Commit[] { }, true);
 
                 repo.Refs.Add("refs/heads/master", commit.Sha);
 
                 Assert.Equal(commit, repo.Head.Tip);
             }
 
-            using (var repo = new Repository(scd.DirectoryPath))
+            using (var repo = new Repository(repoPath))
             {
                 File.WriteAllText(Path.Combine(repo.Info.WorkingDirectory, "a.TxT"), "blah\n");
 
-                var status = repo.Index.RetrieveStatus();
+                var status = repo.RetrieveStatus();
 
-                Assert.Equal(FileStatus.Removed, status["a.txt"]);
-                Assert.Equal(FileStatus.Removed, status["A.TXT"]);
-                Assert.Equal(FileStatus.Untracked, status["a.TxT"]);
+                Assert.Equal(FileStatus.Removed, status["a.txt"].State);
+                Assert.Equal(FileStatus.Removed, status["A.TXT"].State);
+                Assert.Equal(FileStatus.Untracked, status["a.TxT"].State);
             }
         }
 ```

**Comment by yorah** [comment]
Still failing on Windows.

**Test output**

*a.txt* is `Removed`
*A.TXT* is `NonExistent` => this is the unexpected behavior, it should be `Removed` I believe
*a.TxT* is `Untracked`

**Comment by nulltoken** [comment]
@yorah Thanks for this.

@arrbee @ethomson Thoughts?

**Pull request closed without merging**
