### PR TITLE
Proxy options initializing #1429

### PR DESCRIPTION
**Pull request by jwonagel**
Added Factory for initializing Proxyoptions with GitProxyType Auto.
From issue #1429

### CODE REVIEW

**Comment by reegeek** [comment]
hi,

When this PR will be merged ?
Regards,

**Comment by seshonaar** [comment]
Please note that when the port is missing in the proxy URL, libgit2 will crash (default_port is not initialized).

**Comment by seshonaar** [comment]
The issue on the libgit2 side is fixed in master, but not on the maintenance branch (0.28.*), that is used by libgit2sharp

**Comment by jwonagel** [comment]
Proxy can be configured in PushOptions, FetchOptionsBase and RemoteOptions. The behavior does not change.

**Comment by florenzen** [comment]
I would really like to see this Pull Request merged and released. We are using libgit2sharp in an internal tool and have absolutely have to use a proxy. Therefore, I applied the PR branch on the v0.26.2 tag in our fork and it works perfectly (see https://github.com/enertrag/libgit2sharp/releases/tag/v0.26.2_proxy-options). But I'd rather reference a NuGet package than including our own build of this library.

**Pull request closed without merging**
