### PR TITLE
Added IgnoreWhitespaceChange option to MergeOptions;

### PR DESCRIPTION
**Pull request by EVTrifonov**

### CODE REVIEW

**Comment by ethomson** [comment]
Hi @EVTrifonov - this is a nice addition.  It would be nice to have a simple unit test here, is that something that you'd be willing to add?

Thanks!

**Comment by EVTrifonov** [comment]
Hi Edward,

 

                Thank you.

I’ll add unit tests, but due to holidays I’ll do this after January, 4th.

 

Regards,

Evgeny Trifonov

**Comment by adamhwang** [comment]
I really appreciate the PR and added some unit tests for this.

**Comment by EVTrifonov** [comment]
Thank you for unit tests, appreciate too.

**Comment by ethomson** [comment]
Thanks for this!  Manually merged so that I could squash it.

**Comment by EVTrifonov** [comment]
@ethomson, hello.
Are you going to merge this to main branch?

**Comment by ethomson** [comment]
Hi @EVTrifonov - I did merge it, like I mentioned above.

https://github.com/libgit2/libgit2sharp/blob/master/LibGit2Sharp/MergeOptionsBase.cs#L57

**Comment by EVTrifonov** [comment]
Got it, thanks.

**Pull request closed without merging**
