### PR TITLE
Test coverage for branch-only submodule

### PR DESCRIPTION
**Pull request by dahlbyk**
Proves that #604 is fixed.

Also:

* Added `diff` to `Resources/.gitattributes` for commonly-modified text files - respected locally even if GitHub seems to ignore `.gitattributes`.
* Made `remote.origin.url` relative in all `submodule_wd/.git/modules`.
* Added ignore rule for files we don't really need in the Resources repos (e.g. ref logs and `info/exclude`) - fewer files to copy = faster tests.

### CODE REVIEW

**Comment by dahlbyk** [comment]
> Remove extra test resource files

Oops, need reflog for standard repo tests.

**Comment by nulltoken** [comment]
@dahlbyk :cool: :bangbang: Any chance you could simplify the history a bit?

**Comment by dahlbyk** [comment]
Sure, what do you have in mind?

**Comment by nulltoken** [comment]
Maybe squash the last two commits together as the first one doesn't build by itself?

**Comment by nulltoken** [comment]
@dahlbyk ping?

**Comment by dahlbyk** [comment]
Better?

**Comment by nulltoken** [comment]
@jamill @whoisj You're more into submodules than me. Could you please take a look at this PR?

**Comment by whoisj** [comment]
@nulltoken @dahlbyk I will look at this, but today I'm heads down on something else. Can we wait until tomorrow?

**Comment by nulltoken** [comment]
@dahlbyk :heart: 

@whoisj Thanks!

>Can we wait until tomorrow?

I think so. Some of those commits are one year old.

**Comment by whoisj** [comment]
LGTM

@dahlbyk :pray: thanks!

**Comment by nulltoken** [comment]
:ship:'d

**Pull request merged**
