### PR TITLE
Remove manual connection to remote

### PR DESCRIPTION
**Pull request by Therzok**
As seen in https://github.com/libgit2/libgit2/blob/master/src/remote.c#L2381-L2397

### CODE REVIEW

**Comment by Therzok** [comment]
This resulted in double dialog asking for credentials on MonoDevelop, and I traced it back here.

**Comment by carlosmn** [comment]
The connect called from inside `_push()` should be a no-op. If it's connecting twice, that would mean it's a bug in libgit2.

**Comment by Therzok** [comment]
Explanation:

Before, it was not attemping a remote connection if you were connected already to the remote. Now, it always attempts a connection.

**Comment by Therzok** [comment]
This fixes the issue I was having though, so I'm pretty sure it's getting double connection in libgit2 land. I'm getting the credential callback twice, once from git_remote_connect, once from git_remote_push.

**Comment by carlosmn** [comment]
That would mean that `_connect()` tries to connect even though it's already connected, which is a bug, which you're hiding here, rather than fixing.

**Comment by Therzok** [comment]
Opened an issue on libgit2 side. :P Until then, this works for me.

**Comment by nulltoken** [comment]
@Therzok The amazing @carlosmn will work on the libgit2 side. Meanwhile, your proposal is sound. Could you please update your commit, and drop `git_remote_connect()` from the `NativeMethods` and `Proxy` types as well (as `git_remote_free()` takes care of calling it)?

**Comment by Therzok** [comment]
@nulltoken it's not used only there.

`git_remote_connect()` is also used in `Network.ListReferences()`, which libgit2 doesn't seem to handle for connect/disconnect.

Also, https://github.com/libgit2/libgit2/issues/3096 for reference.

**Comment by nulltoken** [comment]
@Therzok Sorry. It was a typo. I meant `_disconnect()`

**Comment by Therzok** [comment]
Done.

**Comment by nulltoken** [comment]
:+1: :banana:

**Comment by nulltoken** [comment]
Published as NuGet pre-release package `LibGit2Sharp.0.22.0-pre20150527180327`

**Pull request merged**
